version: 2
sources:
    - name: source_table_name
      database: "{{('sales')}}"
      schema: raw_schema
      tables:
        - name: raw_customerdata
        - name: emp_sal
        - name: raw_orders
          columns:
            - name: ID
              tests:
                - not_null
                - unique
            - name: STATUS 
              tests:
                - accepted_values:
                   values: ['placed', 'shipped', 'completed', 'returned', 'return_pending','processed']
            - name: user_id
              tests:
                - relationships:
                    to: ref('customers')
                    field: id       

        - name: customers
        
